CREATE TABLE course
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    price       FLOAT                                   NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    status      VARCHAR(255),
    CONSTRAINT pk_course PRIMARY KEY (id)
);

CREATE TABLE course_session
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    course_id   BIGINT                                  NOT NULL,
    order_index INTEGER,
    video_id    BIGINT,
    CONSTRAINT pk_course_session PRIMARY KEY (id)
);

CREATE TABLE video
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    duration INTEGER,
    url      VARCHAR(255),
    CONSTRAINT pk_video PRIMARY KEY (id)
);

ALTER TABLE course_session
    ADD CONSTRAINT uc_course_session_video UNIQUE (video_id);

ALTER TABLE course_session
    ADD CONSTRAINT FK_COURSE_SESSION_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (id);

ALTER TABLE course_session
    ADD CONSTRAINT FK_COURSE_SESSION_ON_VIDEO FOREIGN KEY (video_id) REFERENCES video (id);