CREATE SEQUENCE IF NOT EXISTS student_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE classroom
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    level INTEGER,
    code  VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_classroom PRIMARY KEY (id)
);

CREATE TABLE course
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    code        VARCHAR(255),
    coefficient INTEGER                                 NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_course PRIMARY KEY (id)
);

CREATE TABLE enrollment
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status          VARCHAR(255),
    enrollment_date TIMESTAMP WITHOUT TIME ZONE,
    session_id      BIGINT                                  NOT NULL,
    student_id      INTEGER                                 NOT NULL,
    CONSTRAINT pk_enrollment PRIMARY KEY (id)
);

CREATE TABLE instructor
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lastname   VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    speciality VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_instructor PRIMARY KEY (id)
);

CREATE TABLE session
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description   VARCHAR(255),
    start_date    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date      TIMESTAMP WITHOUT TIME ZONE,
    status        SMALLINT,
    capacity      INTEGER,
    course_id     BIGINT                                  NOT NULL,
    instructor_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_session PRIMARY KEY (id)
);

CREATE TABLE student
(
    id        INTEGER      NOT NULL,
    lastname  VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    email     VARCHAR(255),
    CONSTRAINT pk_student PRIMARY KEY (id)
);

ALTER TABLE classroom
    ADD CONSTRAINT uc_classroom_code UNIQUE (code);

ALTER TABLE course
    ADD CONSTRAINT uc_course_code UNIQUE (code);

ALTER TABLE instructor
    ADD CONSTRAINT uc_instructor_email UNIQUE (email);

ALTER TABLE student
    ADD CONSTRAINT uc_student_email UNIQUE (email);

CREATE INDEX idx_course_code ON course (code);

CREATE INDEX idx_course_name ON course (name);

CREATE INDEX idx_instructor_email ON instructor (email);

CREATE INDEX idx_session_enddate ON session (end_date);

CREATE INDEX idx_session_startdate ON session (start_date);

ALTER TABLE enrollment
    ADD CONSTRAINT FK_ENROLLMENT_ON_SESSION FOREIGN KEY (session_id) REFERENCES session (id);

ALTER TABLE enrollment
    ADD CONSTRAINT FK_ENROLLMENT_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);

ALTER TABLE session
    ADD CONSTRAINT FK_SESSION_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (id);

ALTER TABLE session
    ADD CONSTRAINT FK_SESSION_ON_INSTRUCTOR FOREIGN KEY (instructor_id) REFERENCES instructor (id);