CREATE TABLE certificate
(
    id        UUID NOT NULL,
    reference VARCHAR(255),
    url       VARCHAR(255),
    CONSTRAINT pk_certificate PRIMARY KEY (id)
);

CREATE TABLE resource
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    video_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_resource PRIMARY KEY (id)
);

CREATE TABLE student
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email       VARCHAR(255),
    password    VARCHAR(255),
    lastname    VARCHAR(255),
    firstname   VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_student PRIMARY KEY (id)
);

CREATE TABLE video_progress
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    video_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_video_progress PRIMARY KEY (id)
);

ALTER TABLE video
    ADD title VARCHAR(255);

ALTER TABLE video
    ALTER COLUMN title SET NOT NULL;

ALTER TABLE certificate
    ADD CONSTRAINT uc_certificate_reference UNIQUE (reference);

ALTER TABLE video_progress
    ADD CONSTRAINT uc_video_progress_video UNIQUE (video_id);

ALTER TABLE resource
    ADD CONSTRAINT FK_RESOURCE_ON_VIDEO FOREIGN KEY (video_id) REFERENCES video (id);

ALTER TABLE video_progress
    ADD CONSTRAINT FK_VIDEO_PROGRESS_ON_VIDEO FOREIGN KEY (video_id) REFERENCES video (id);