CREATE TABLE enrollment
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id   BIGINT                                  NOT NULL,
    student_id  BIGINT                                  NOT NULL,
    enrolled_at TIMESTAMP WITHOUT TIME ZONE,
    progress    INTEGER,
    completed   BOOLEAN,
    CONSTRAINT pk_enrollment PRIMARY KEY (id)
);

CREATE TABLE payment
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id   BIGINT                                  NOT NULL,
    course_id    BIGINT                                  NOT NULL,
    amount       DECIMAL,
    status       SMALLINT,
    payment_date TIMESTAMP WITHOUT TIME ZONE,
    provider     SMALLINT,
    CONSTRAINT pk_payment PRIMARY KEY (id)
);

ALTER TABLE video_progress
    ADD is_completed BOOLEAN;

ALTER TABLE video_progress
    ADD last_time_visualized VARCHAR(255);

ALTER TABLE video_progress
    ADD student_id BIGINT;

ALTER TABLE video_progress
    ALTER COLUMN student_id SET NOT NULL;

CREATE UNIQUE INDEX IX_pk_student ON student (id, id);

ALTER TABLE enrollment
    ADD CONSTRAINT FK_ENROLLMENT_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (id);

ALTER TABLE enrollment
    ADD CONSTRAINT FK_ENROLLMENT_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);

ALTER TABLE payment
    ADD CONSTRAINT FK_PAYMENT_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (id);

ALTER TABLE payment
    ADD CONSTRAINT FK_PAYMENT_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);

ALTER TABLE video_progress
    ADD CONSTRAINT FK_VIDEO_PROGRESS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);