CREATE TABLE instructor
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email       VARCHAR(255),
    password    VARCHAR(255),
    description OID,
    CONSTRAINT pk_instructor PRIMARY KEY (id)
);

ALTER TABLE course
    ADD image VARCHAR(255);

ALTER TABLE course
    ADD instructor_id BIGINT;

ALTER TABLE course
    ALTER COLUMN image SET NOT NULL;

ALTER TABLE course
    ADD CONSTRAINT FK_COURSE_ON_INSTRUCTOR FOREIGN KEY (instructor_id) REFERENCES instructor (id);