CREATE TABLE favorite
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id  BIGINT,
    student_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_favorite PRIMARY KEY (id)
);

CREATE TABLE opinion
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id  BIGINT                                  NOT NULL,
    student_id BIGINT                                  NOT NULL,
    comment    TEXT,
    rating     INTEGER,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_opinion PRIMARY KEY (id)
);

ALTER TABLE favorite
    ADD CONSTRAINT FK_FAVORITE_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (id);

ALTER TABLE favorite
    ADD CONSTRAINT FK_FAVORITE_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);

ALTER TABLE opinion
    ADD CONSTRAINT FK_OPINION_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (id);

ALTER TABLE opinion
    ADD CONSTRAINT FK_OPINION_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);